### ISSUE TITLE
Merge permission for @bdw429s

### ISSUE THREAD

**Issue by Insti** [exercism/coldfusion#29]
Is there anyone who can give @bdw429s merge permission on this repository?
He's doing a great job of getting it set up and it would be easier if he could merge his PRs.

Or are there any previous committers out there who can help out?

@kytrinyx, @catb0t , @cgrayson and @nelsnich  have all committed to this repository in the past and might still have the relevant permissions.

Thanks.

**Comment by kytrinyx** [comment]
Oh! I thought I had given your merge on the repo. One sec while I fix that!

**Comment by kytrinyx** [comment]
I've been working on a bot that will let track maintainers maintain their own maintainer teams via PRs to the maintainers.json config file. I've been slammed at work (and with v2) so I haven't gotten the finishing touches on it. So close though.

@bdw429s - you have a pending invitation

**Comment by bdw429s** [comment]
Oh man, that would have made the last 10 day a lot easier! :) Thx!

**Comment by Insti** [comment]
🚂 Full steam ahead :tada:
